<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="3" passed="1" failed="2" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[<div style="display:block;margin-left:10px;"></div>]]>
    </line>
    <line>
      <![CDATA[<div style="display:block;margin-left:10px;"></div>]]>
    </line>
    <line>
      <![CDATA[<div style="display:block;margin-left:10px;"></div>]]>
    </line>
    <line>
      <![CDATA[<div style="display:block;margin-left:10px;"></div>]]>
    </line>
    <line>
      <![CDATA[<div style="display:block;margin-left:10px;"></div>]]>
    </line>
    <line>
      <![CDATA[<div style="display:block;margin-left:10px;"></div>]]>
    </line>
  </reporter-output>
  <suite started-at="2019-04-19T09:37:01Z" name="Default suite" finished-at="2019-04-19T09:37:01Z" duration-ms="81">
    <groups>
      <group name="Regression">
        <method signature="TestAuthentication.failedAuthenticationTest(java.lang.String)[pri:0, instance:TestNGmavenexemple.TestAuthentication@3c7f66c4]" name="failedAuthenticationTest" class="TestNGmavenexemple.TestAuthentication"/>
        <method signature="TestAuthentication.validAuthenticationTest()[pri:0, instance:TestNGmavenexemple.TestAuthentication@3c7f66c4]" name="validAuthenticationTest" class="TestNGmavenexemple.TestAuthentication"/>
      </group> <!-- Regression -->
      <group name="Sniff">
        <method signature="TestAuthentication.newUserAuthenticationTest(java.lang.String)[pri:0, instance:TestNGmavenexemple.TestAuthentication@3c7f66c4]" name="newUserAuthenticationTest" class="TestNGmavenexemple.TestAuthentication"/>
        <method signature="TestAuthentication.validAuthenticationTest()[pri:0, instance:TestNGmavenexemple.TestAuthentication@3c7f66c4]" name="validAuthenticationTest" class="TestNGmavenexemple.TestAuthentication"/>
      </group> <!-- Sniff -->
    </groups>
    <test started-at="2019-04-19T09:37:01Z" name="Default test" finished-at="2019-04-19T09:37:01Z" duration-ms="81">
      <class name="TestNGmavenexemple.TestAuthentication">
        <test-method signature="failedAuthenticationTest(java.lang.String)[pri:0, instance:TestNGmavenexemple.TestAuthentication@3c7f66c4]" started-at="2019-04-19T11:37:01Z" name="failedAuthenticationTest" finished-at="2019-04-19T11:37:01Z" duration-ms="0" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[wrong number of arguments]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: wrong number of arguments
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:135)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:426)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failedAuthenticationTest -->
        <test-method signature="newUserAuthenticationTest(java.lang.String)[pri:0, instance:TestNGmavenexemple.TestAuthentication@3c7f66c4]" started-at="2019-04-19T11:37:01Z" name="newUserAuthenticationTest" finished-at="2019-04-19T11:37:01Z" duration-ms="0" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[wrong number of arguments]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: wrong number of arguments
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:135)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:426)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- newUserAuthenticationTest -->
        <test-method signature="validAuthenticationTest()[pri:0, instance:TestNGmavenexemple.TestAuthentication@3c7f66c4]" started-at="2019-04-19T11:37:01Z" name="validAuthenticationTest" finished-at="2019-04-19T11:37:01Z" duration-ms="0" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[<div style="display:block;margin-left:10px;"></div>]]>
            </line>
            <line>
              <![CDATA[<div style="display:block;margin-left:10px;"></div>]]>
            </line>
          </reporter-output>
        </test-method> <!-- validAuthenticationTest -->
      </class> <!-- TestNGmavenexemple.TestAuthentication -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
